Covid19London/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('plots/', include('plots.urls')),
]

plots/urls.py
from django.urls import path

from . import views

app_name = 'plots'
urlpatterns = [
	path('', views.index, name='index'),
	path('London/abs/<borough_name>/', views.cumul_abs, name='cumulative_single'),
	path('London/rel/', views.cumul_rel, name='cumulative_multiple'),
	path('London/trends/<borough_name>/', views.trends, name='trends'),
	path('Italy/abs/<province_name>/', views.cumul_ita, name='cumulative_italy'),
	path('Italy/trends/<province_name>/', views.trends_ita, name='trends_italy'),
]

plots/models.py
from django.contrib.postgres.fields import ArrayField
from django.db import models

from datetime import datetime
import numpy as np

# Abstract model for data of regional areas
class RegionalArea(models.Model):
	name = models.CharField(max_length=200)
	population = models.IntegerField(default=0)
	cumulative_array = ArrayField(models.IntegerField())

	def __str__(self):
		return self.name

	def get_single_entry(self,index):
		size_array = len(self.cumulative_array)

		if (index >= size_array) or (index <= -size_array-1):
			raise IndexError

		return self.cumulative_array[index]

	class Meta:
		abstract = True

# Model for saving cumulative cases of London's boroughs
class Borough(RegionalArea):

	latest_deaths = models.IntegerField(default=0)

	class Meta(RegionalArea.Meta):
		db_table = 'London_boroughs'

# Model for saving cumulative cases of Italian province
class Province(RegionalArea):

	class Meta(RegionalArea.Meta):
		db_table = 'Italy_provinces'

# Abstract model for dates since first infection
class Dates(models.Model):
	dates_array = ArrayField(models.CharField(max_length=200))

	def get_dates(self,date_format):
		date_object_array = [datetime.strptime(date,'%d-%b-%Y') for date in self.dates_array]
		return np.array([date_object.strftime(date_format) for date_object in date_object_array])

	def get_single_date(self,index):
		date_object_array = [datetime.strptime(date,'%d-%b-%Y') for date in self.dates_array]
		size_array = len(date_object_array)

		if (index >= size_array) or (index <= -size_array-1):
			raise IndexError

		return date_object_array[index]

	def get_single_date_str(self,index,date_format):
		date_object = self.get_single_date(index)
		return date_object.strftime(date_format)

	class Meta:
		abstract = True

# Model of dates since first infection London
class LondonDate(Dates):

	class Meta(Dates.Meta):
		db_table = 'London_dates'

# Model of dates since first infection Italy
class ItalyDate(Dates):

	class Meta(Dates.Meta):
		db_table = 'Italy_dates'

# Model to collect user data requests
class DateCases(models.Model):
	date = models.DateField()

plots/forms.py
from django import forms
from django.forms import ModelForm

from .models import DateCases

from datetime import date

class DateInput(forms.DateInput):
	input_type = 'date'

class DailyCasesForm(ModelForm):

	class Meta:
		model = DateCases
		fields = ['date']
		widgets = {
		    'date': DateInput(),
		}

plots/views.py
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render
from django.urls import reverse

from .plots_lib import cumulative_cases, relative_cases, regions_trends
from .models import Borough, Province, LondonDate, ItalyDate

def index(request):
	return HttpResponseRedirect(reverse('plots:cumulative_single', args=('London',)))

## LONDON VIEWS

def cumul_abs(request,borough_name):
	context = cumulative_cases(request,LondonDate,Borough,borough_name)

	# London boroughs have information on the total deaths to date
	b = Borough.objects.get(name__exact=borough_name)
	
	context['tot_deaths']=b.latest_deaths
	context['tot_cases']=b.get_single_entry(-1)
	context['mortality']="{:.1f}".format(100*context['tot_deaths']/context['tot_cases'])

	return render(request, 'plots/cumulative_abs.html', context)

def cumul_rel(request):
	context = relative_cases(request,LondonDate,Borough)
	return render(request, 'plots/cumulative_rel.html', context)

def trends(request,borough_name):
	context = regions_trends(request,LondonDate,Borough,borough_name)
	return render(request, 'plots/trends.html', context)

## ITALY VIEWS

def cumul_ita(request,province_name):
	context = cumulative_cases(request,ItalyDate,Province,province_name)
	return render(request, 'plots/cumulative_italy.html', context)

def trends_ita(request,province_name):
	context = regions_trends(request,ItalyDate,Province,province_name)
	return render(request, 'plots/trends_italy.html', context)

plots/templates/plots/cumulative_abs.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'plots/style.css' %}">

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
  <div class="container-fluid">
    <h2>Cumulative cases in London boroughs</h2>
    <p>
      This page shows the cumulative cases of Covid-19 in different London boroughs.
      The data are collected from the governmental website 
      <a href="https://coronavirus.data.gov.uk">https://coronavirus.data.gov.uk</a>.
      The data are updated to <b>{{ date }}</b>.
    </p>
    <div class="dropdown">
    	<button class="dropbtn">{{ current }}</button>
    		<div class="dropdown-content">
    			{% for entry in items %}
    					<a href="{% url 'plots:cumulative_single' entry %}">{{ entry }}</a>
    			{% endfor %}
    		</div>
    </div>
    <div align="center" id="daily">
      <p>
        <b>Total cases:</b> {{ tot_cases }} &emsp;
        <b>Total deaths:</b> {{ tot_deaths }} &emsp;
        <nobr><b>Mortality rate:</b> {{ mortality }}&#37;</nobr>
      </p>
    </div>
    <div id="image">
    	<img src="data:image/png;base64,{{ data }}" alt="">
    </div>
    <div align="center" id="daily">
      <form method = "GET">
        {{ date_form }} 
        <input type = "submit" value = "Show cases"> 
      </form>
      <p>
        <b>Total cases to date:</b> {{ daily_tot }} &emsp;
        <b>Daily increase:</b> {{ daily_inc }} &emsp;
        <b>Percentual increase:</b> {{ daily_per }}&#37;
      </p>
    </div>
    <p>
      <b>NOTE:</b>
        <ol>
        <li>
          The blue line represents the cumulative number of Covid-19 cases recorded in the borough. The values taken by this line are shown on the left y-axis.
        </li>
        <li>
          The green bars are the daily cases recorded. The value of these bars can be read on the
          right y-axis.
        </li>
        <li>
          The light green bars are definitive data, while the dark green ones are provisional and will likely be updated in the coming days.
        </li>
        <li>
          The red line is the moving average of daily cases with a 7-day period, to remove
          fluctuations due to delays during the weekends.
        </li>
      </ol>
    </p>
    <p align="right">
      <a href="{% url 'plots:cumulative_multiple' %}">Relative cumulative cases</a> &#x21E8;
    </p>
    <p align="right">
      <a href="{% url 'plots:trends' 'London' %}">Compare London boroughs</a> &#x21E8;
    </p>
    <hr>
    <p id="footnote">
      This project was made using Django, and the source code can be found on
      <a href="https://github.com/carlosparaciari/Covid19London">GitHub</a>.
      <span style="float:right;" >
        <a href="{% url 'plots:cumulative_italy' 'Milano' %}">&#x1f1ee;&#x1f1f9;</a>
      </span>
    </p>
  </div>
</body>

plots/templates/plots/cumulative_italy.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'plots/style.css' %}">

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
  <div class="container-fluid">
    <h2>Cumulative cases in Italian provinces</h2>
    <p>
      This page shows the cumulative cases of Covid-19 in different Italian provinces.
      The data are collected from the Protezione Civile Italina 
      (<a href="https://github.com/pcm-dpc/COVID-19">link</a>).
      The data are updated to <b>{{ date }}</b>.
    </p>
    <div class="dropdown">
      <button onclick="click_search()" class="dropbtn">{{ current }}</button>
      <div id="src_dropdown" class="dropdown-content">
        <input type="text" placeholder=" Select province..." id="src_input" onkeyup="filter_search()">
        {% for entry in items %}
            <a href="{% url 'plots:cumulative_italy' entry %}">{{ entry }}</a>
        {% endfor %}
      </div>
    </div>
    <div id="image">
    	<img src="data:image/png;base64,{{ data }}" alt="">
    </div>
    <div align="center" id="daily">
      <form method = "GET">
        {{ date_form }} 
        <input type = "submit" value = "Show cases"> 
      </form>
      <p>
        <b>Total cases to date:</b> {{ daily_tot }} &emsp;
        <b>Daily increase:</b> {{ daily_inc }} &emsp;
        <b>Percentual increase:</b> {{ daily_per }}&#37;
      </p>
    </div>
    <p>
      <b>NOTE:</b>
        <ol>
        <li>
          The blue line represents the cumulative number of Covid-19 cases recorded in the province. The values taken by this line are shown on the left y-axis.
        </li>
        <li>
          The green bars are the daily cases recorded. The value of these bars can be read on the
          right y-axis.
        </li>
        <li>
          The red line is the moving average of daily cases with a 7-day period, to remove
          fluctuations due to delays during the weekends.
        </li>
      </ol>
    </p>
    <p align="right">
      <a href="{% url 'plots:trends_italy' 'Milano' %}">Compare Italian provinces</a> &#x21E8;
    </p>
    <hr>
    <p id="footnote">
      This project was made using Django, and the source code can be found on
      <a href="https://github.com/carlosparaciari/Covid19London">GitHub</a>.
      <span style="float:right;" >
        <a href="{% url 'plots:cumulative_single' 'London' %}">&#x1f1ec;&#x1f1e7;</a>
      </span>
    </p>
  </div>

<script>
function click_search() {
  document.getElementById("src_dropdown").classList.toggle("show");
}

function filter_search() {
  var input, filter, ul, li, a, i;
  input = document.getElementById("src_input");
  filter = input.value.toUpperCase();
  div = document.getElementById("src_dropdown");
  a = div.getElementsByTagName("a");
  for (i = 0; i < a.length; i++) {
    txtValue = a[i].textContent || a[i].innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      a[i].style.display = "";
    } else {
      a[i].style.display = "none";
    }
  }
}
</script>

</body>

plots/templates/plots/cumulative_rel.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'plots/style.css' %}">

<!DOCTYPE html>
<html>
<head>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
	<div class="container-fluid">
		<h2>Comparison between cases in London boroughs</h2>
		<p>
			This page shows a comparison between cumulative cases of Covid-19 in different London boroughs.
			The data are collected from the governmental website 
			<a href="https://coronavirus.data.gov.uk">https://coronavirus.data.gov.uk</a>.
			The data are updated to <b>{{ date }}</b>.
		</p>
		<div class="row">
			<div class="col-md-3 col-xs-12">
				<p>Select boroughs to compare:</p>
	    	<form action="{% url 'plots:cumulative_multiple' %}" method="post">
					<div id="checkbox_list">
						{% csrf_token %}
						{% for entry in items %}
						<input type="checkbox" name="{{ entry.0 }}" value="compare" {% if entry.1 %}checked{% endif %}>
						  <label for="{{ entry.0 }}" id="checkbox_entry">{{ entry.0 }}</label><br>
						{% endfor %}
						<input type="submit" value="Compare boroughs" id="submit_button">
					</div>
				</form>
			</div>
			<div class="col-md-9 col-xs-12" id="right_column">
				<img src="data:image/png;base64,{{ data }}" alt="">
				<p align="left">
					<b>NOTE:</b>
					<ol align="left">
					<li>
						To allow for comparing cases between different boroughs, the number of cases is taken relative to 100,000 people.
					</li>
					<li>
						To normalise the cases we have used the latest population estimates (2018) released by the <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates">Office of National Statistics</a>.
					</li>
					<li>
						Rather than showing the cases by date, we show them by days passed since the first relative case occurred.
					</li>
					</ol>
				</p>
			</div>
		</div>
		<p align="right">
	    	<a href="{% url 'plots:cumulative_single' 'London' %}">Absolute cumulative cases</a> &#x21E8;
		</p>
    	<p align="right">
      		<a href="{% url 'plots:trends' 'London' %}">Compare London boroughs</a> &#x21E8;
    	</p>
		<hr>
	    <p id="footnote">
		      This project was made using Django, and the source code can be found on
		      <a href="https://github.com/carlosparaciari/Covid19London">GitHub</a>.
		      <span style="float:right;" >
		        	<a href="{% url 'plots:cumulative_italy' 'Milano' %}">&#x1f1ee;&#x1f1f9;</a>
		      </span>
	    </p>
	</div>
</body>

plots/templates/plots/trends.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'plots/style.css' %}">

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
  <div class="container-fluid">
    <h2>Covid-19 trends in London boroughs</h2>
    <p>
      This page shows how the differen boroughs perform in terms of
      total cases of Covid-19 and their weekly increments.
      The data are collected from the governmental website 
      <a href="https://coronavirus.data.gov.uk">https://coronavirus.data.gov.uk</a>.
      The data are updated to <b>{{ date }}</b>.
    </p>
    <div class="dropdown">
      <button class="dropbtn">{{ current }}</button>
        <div class="dropdown-content">
          {% for entry in items %}
              <a href="{% url 'plots:trends' entry %}">{{ entry }}</a>
          {% endfor %}
        </div>
    </div>
    <div id="image">
    	<img src="data:image/png;base64,{{ data }}" alt="">
    </div>
    <div align="center" id="daily">
      <p>
        <b>Total cases to date:</b> {{ tot_cases }} per {{ rel_num }} people &emsp;
        <b>Weekly increase:</b> {{ weekly_inc }} per {{ rel_num }} people
      </p>
    </div>
    <p>
      <b>NOTE:</b>
        <ol>
        <li>
          On the x-axis we show the total number of Covid-19 cases registered to
          date per {{ rel_num }} people. On the y-axis we show the increment of
          cases registered during the last 7 days per {{ rel_num }} people.
        </li>
        <li>
          To normalise the cases we have used the latest population estimates (2018) released by the <a href="https://www.ons.gov.uk/peoplepopulationandcommunity/populationandmigration/populationestimates">Office of National Statistics</a>.
        </li>
        <li>
          Each grey point represents a different London borough. The boroughs with both the highest number of cases and the highest weekly increment are highlighted in red; those with high cases and low increments (or viceversa) are shown in orange. The boroughs with the lowest number of cases and the lowest weekly increment are highlighted in green. 
        </li>
        <li>
          The black point in between the dashed line represents the average between boroughs (i.e., London). The borough of interest (the one requested via the button) is highlighted with a blue cross.
        </li>
      </ol>
    </p>
    <p align="right">
      <a href="{% url 'plots:cumulative_single' 'London' %}">Absolute cumulative cases</a> &#x21E8;
    </p>
    <p align="right">
      <a href="{% url 'plots:cumulative_multiple' %}">Relative cumulative cases</a> &#x21E8;
    </p>
    <hr>
    <p id="footnote">
      This project was made using Django, and the source code can be found on
      <a href="https://github.com/carlosparaciari/Covid19London">GitHub</a>.
      <span style="float:right;" >
        <a href="{% url 'plots:cumulative_italy' 'Milano' %}">&#x1f1ee;&#x1f1f9;</a>
      </span>
    </p>
  </div>
</body>

plots/templates/plots/trends_italy.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'plots/style.css' %}">

<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" />
</head>
<body>
  <div class="container-fluid">
    <h2>Covid-19 trends in Italian provinces</h2>
    <p>
      This page shows how the differen provinces perform in terms of
      total cases of Covid-19 and their weekly increments.
      The data are collected from the Protezione Civile Italina 
      (<a href="https://github.com/pcm-dpc/COVID-19">link</a>).
      The data are updated to <b>{{ date }}</b>.
    </p>
    <div class="dropdown">
      <button onclick="click_search()" class="dropbtn">{{ current }}</button>
      <div id="src_dropdown" class="dropdown-content">
        <input type="text" placeholder=" Select province..." id="src_input" onkeyup="filter_search()">
        {% for entry in items %}
            <a href="{% url 'plots:trends_italy' entry %}">{{ entry }}</a>
        {% endfor %}
      </div>
    </div>
    <div id="image">
    	<img src="data:image/png;base64,{{ data }}" alt="">
    </div>
    <div align="center" id="daily">
      <p>
        <b>Total cases to date:</b> {{ tot_cases }} per {{ rel_num }} people &emsp;
        <b>Weekly increase:</b> {{ weekly_inc }} per {{ rel_num }} people
      </p>
    </div>
    <p>
      <b>NOTE:</b>
        <ol>
        <li>
          On the x-axis we show the total number of Covid-19 cases registered to
          date per {{ rel_num }} people. On the y-axis we show the increment of
          cases registered during the last 7 days per {{ rel_num }} people.
        </li>
        <li>
          To normalise the cases we have used the latest population estimates (2020) released by the <a href="http://dati.istat.it/Index.aspx?DataSetCode=DCIS_POPRES1">Istituto nazionale di statistica</a>.
        </li>
        <li>
          Each grey point represents a different Italian province. The provinces with both the highest number of cases and the highest weekly increment are highlighted in red; those with high cases and low increments (or viceversa) are shown in orange. The provinces with the lowest number of cases and the lowest weekly increment are highlighted in green. 
        </li>
        <li>
          The black point in between the dashed line represents the average between provinces (i.e., Italy). The province of interest (the one requested via the button) is highlighted with a blue cross.
        </li>
      </ol>
    </p>
    <p align="right">
      <a href="{% url 'plots:cumulative_italy' 'Milano' %}">Absolute cumulative cases</a> &#x21E8;
    </p>
    <hr>
    <p id="footnote">
      This project was made using Django, and the source code can be found on
      <a href="https://github.com/carlosparaciari/Covid19London">GitHub</a>.
      <span style="float:right;" >
        <a href="{% url 'plots:cumulative_single' 'London' %}">&#x1f1ec;&#x1f1e7;</a>
      </span>
    </p>
  </div>

<script>
function click_search() {
  document.getElementById("src_dropdown").classList.toggle("show");
}

function filter_search() {
  var input, filter, ul, li, a, i;
  input = document.getElementById("src_input");
  filter = input.value.toUpperCase();
  div = document.getElementById("src_dropdown");
  a = div.getElementsByTagName("a");
  for (i = 0; i < a.length; i++) {
    txtValue = a[i].textContent || a[i].innerText;
    if (txtValue.toUpperCase().indexOf(filter) > -1) {
      a[i].style.display = "";
    } else {
      a[i].style.display = "none";
    }
  }
}
</script>

</body>